# https://github.com/k1LoW/octocov?tab=readme-ov-file#configuration
coverage:
  acceptable: current >= 70%
  paths:
    - coverage.xml
codeToTestRatio:
  acceptable: 1:0.5
  code:
    - "**/*.py"
    - "!.venv/**/*.py"
    - "!tests/**/*.py"
  test:
    - "tests/**/*.py"
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
  updatePrevious: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
